services:
  - type: web
    name: backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    ports:
      - 3001
